//! Offline policy authoring helpers (draft / tighten).
//!
//! AI may only emit proposed YAML for human review — never silent Allow at runtime.
//! Host agents (MCP) refine drafts; CLI uses deterministic heuristics.

use std::collections::HashMap;

use crate::argv::ParsedCommand;
use crate::packs::PACK_NAMES;
use crate::policy::Decision;
use crate::receipts::Receipt;

/// Draft a policy YAML from a natural-language intent (deterministic heuristics).
/// MCP hosts can refine the proposal with their own model before the human writes it.
pub fn draft_policy(intent: &str) -> Result<String, String> {
    Ok(heuristic_draft(intent))
}

fn heuristic_draft(intent: &str) -> String {
    let lower = intent.to_ascii_lowercase();
    let mut extends: Vec<&str> = vec!["dangerous-defaults", "shell-basics"];
    if lower.contains("rust") || lower.contains("cargo") {
        extends.push("rust-dev");
    }
    if lower.contains("node")
        || lower.contains("npm")
        || lower.contains("pnpm")
        || lower.contains("yarn")
        || lower.contains("typescript")
        || lower.contains("javascript")
    {
        extends.push("node-dev");
    }
    if lower.contains("python") || lower.contains("pytest") || lower.contains("pip") {
        extends.push("python-dev");
    }
    if lower.contains("golang") || lower.contains(" go ") || lower.starts_with("go ") || lower.contains("go.")
    {
        extends.push("go-dev");
    }
    if lower.contains("java") || lower.contains("maven") || lower.contains("gradle") {
        extends.push("java-dev");
    }
    if lower.contains("dotnet") || lower.contains(".net") || lower.contains("csharp") || lower.contains("c#")
    {
        extends.push("dotnet-dev");
    }
    if lower.contains("c++") || lower.contains("cmake") || lower.contains("cpp") {
        extends.push("cpp-dev");
    }
    if lower.contains("php") || lower.contains("composer") {
        extends.push("php-dev");
    }
    if lower.contains("ruby") || lower.contains("bundler") || lower.contains("gemfile") {
        extends.push("ruby-dev");
    }
    if lower.contains("kotlin") || lower.contains("android") {
        extends.push("kotlin-dev");
    }
    if lower.contains("git") || extends.len() == 2 {
        extends.push("git-safe");
    }
    if lower.contains("kuber")
        || lower.contains("kubectl")
        || lower.contains("terraform")
        || lower.contains("docker")
        || lower.contains("ops")
    {
        extends.push("ops-approve");
    }
    // Dedupe while preserving order
    let mut seen = std::collections::HashSet::new();
    extends.retain(|e| seen.insert(*e));

    let mut rules = String::new();
    if lower.contains("deny") && lower.contains("force") {
        rules.push_str(
            r#"
  - id: local.deny-force-push
    effect: deny
    reason: "User intent: deny force push"
    match:
      argv: { binary: git, args_prefix: [push], flags_any: ["--force", "-f"] }
"#,
        );
    }

    let extends_yaml = extends
        .iter()
        .map(|e| format!("  - pack: {e}"))
        .collect::<Vec<_>>()
        .join("\n");

    let rules_block = if rules.trim().is_empty() {
        String::new()
    } else {
        format!("rules:{rules}")
    };

    format!(
        r#"# Generated by `mayrun policy draft` — review before use.
# Intent: {intent}
# Packs available: {packs}
apiVersion: mayrun.dev/v1
default: deny
extends:
{extends_yaml}
{rules_block}"#,
        intent = intent,
        packs = PACK_NAMES.join(", "),
        extends_yaml = extends_yaml,
        rules_block = rules_block,
    )
}

/// Propose policy rule snippets from receipt history (deterministic).
pub fn tighten_from_receipts(receipts: &[Receipt], min_count: usize) -> String {
    let mut approved: HashMap<String, usize> = HashMap::new();
    let mut denied_unmatched: HashMap<String, usize> = HashMap::new();

    for r in receipts {
        let parsed = ParsedCommand::parse(&r.command);
        let key = if parsed.binary.is_empty() {
            r.command.clone()
        } else {
            let mut parts = vec![parsed.binary.clone()];
            parts.extend(parsed.args().iter().take(2).cloned());
            parts.join(" ")
        };
        match r.decision {
            Decision::RequireApproval if r.approved => {
                *approved.entry(key).or_default() += 1;
            }
            Decision::Deny
                if r.rule_id.is_none()
                    || r.rule_id
                        .as_deref()
                        .is_some_and(|id| id.starts_with("default")) =>
            {
                *denied_unmatched.entry(key).or_default() += 1;
            }
            Decision::Deny
                if r.reason
                    .as_deref()
                    .is_some_and(|s| s.starts_with("default:")) =>
            {
                *denied_unmatched.entry(key).or_default() += 1;
            }
            _ => {}
        }
    }

    let mut out = String::from(
        "# Proposed rules from `mayrun policy tighten` — review before merging.\nrules:\n",
    );
    let mut any = false;

    let mut approved_list: Vec<_> = approved.into_iter().collect();
    approved_list.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));
    for (cmd, count) in approved_list {
        if count < min_count {
            continue;
        }
        any = true;
        let parsed = ParsedCommand::parse(&cmd);
        let id = sanitize_id(&format!("tighten.allow.{}", parsed.binary));
        let prefix = yaml_str_list(parsed.args().iter().take(1).map(|s| s.as_str()));
        out.push_str(&format!(
            "  # seen {count}x as human-approved\n  - id: {id}\n    effect: allow\n    reason: \"Frequently approved: {cmd}\"\n    match:\n      argv: {{ binary: {}, args_prefix: {prefix} }}\n",
            parsed.binary
        ));
    }

    let mut denied_list: Vec<_> = denied_unmatched.into_iter().collect();
    denied_list.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));
    for (cmd, count) in denied_list {
        if count < min_count {
            continue;
        }
        any = true;
        let parsed = ParsedCommand::parse(&cmd);
        if parsed.binary.is_empty() {
            continue;
        }
        let id = sanitize_id(&format!("tighten.allow.{}", parsed.binary));
        out.push_str(&format!(
            "  # default-denied {count}x — consider allow if intentional\n  - id: {id}\n    effect: allow\n    reason: \"Repeatedly attempted: {cmd}\"\n    match:\n      argv: {{ binary: {} }}\n",
            parsed.binary
        ));
    }

    if !any {
        out.push_str("  # (no patterns met the frequency threshold)\n");
    }
    out
}

fn sanitize_id(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '.' || c == '-' || c == '_' {
                c
            } else {
                '-'
            }
        })
        .collect()
}

fn yaml_str_list<'a>(items: impl IntoIterator<Item = &'a str>) -> String {
    let parts: Vec<String> = items
        .into_iter()
        .map(|s| format!("\"{s}\""))
        .collect();
    format!("[{}]", parts.join(", "))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn heuristic_picks_rust_pack() {
        let y = heuristic_draft("allow local cargo and git; deny force push");
        assert!(y.contains("rust-dev"));
        assert!(y.contains("git-safe"));
        assert!(y.contains("dangerous-defaults"));
        assert!(y.contains("local.deny-force-push"));
    }
}
